module.exports = {
    CATEGORY_ALREADY_EXISTS: 'Категорія вже існує',
    CHECK_THE_DATA: 'Перевірте дані',
    CHANGE_PASSWORD: 'Для зміни пароля заповніть поля',
    CONFLICT_EMAIL: 'Така пошта не зареєстрована',
    CREATED: 'Користувач створений',
    DATA_IS_SAVED: 'Дані збережені',
    DELETE_USER: 'Користувач видалений',
    EMPTY_FIELDS: 'Перевірте незаповнені поля',
    ENTER_THE_INVENTORY_NUMBER: 'Введіть інвентарний номер',
    FILL_FIELDS: 'Заповніть поля',
    INCORRECT_EMAIL: 'Некоректна пошта',
    INCORRECT_DATA: 'Некоректні дані',
    INCORRECT_PASSWORD: 'Не правильний пароль',
    INVALID_INVENTORY_NUMBER: 'Не правильний інвентарний номер',
    INVENTORY_NUMBER_IS_ALREADY_USED: 'Інвентарний номер вже використаний',
    MINIMUM_LENGTH_PASSWORD: 'Мінімальна дожина пароля 6 символів',
    NOT_CATEGORY: 'Не має категорії',
    NOT_CREATE_ORDER: 'Помилка оформлення замовлення',
    NOT_CREATE_ORDER_IN_ARCHIVE: 'Помилка перенесення в архів',
    NOT_FIND_ORDER: 'Замовлення відсутнє',
    NOT_FOUND: 'Користувач відсутній',
    NOT_FOUND_DATA: 'Дані відсутні',
    NOT_FOUNDS: 'Користувачі відсутні',
    NOT_ORDER: 'Не має замовлень',
    NOT_PRODUCT: 'Не має продуктів',
    NOT_STATUS: 'Статус відсутній',
    NOT_UPDATE_DATA: 'Дані не змінені',
    NOT_UPDATE_STATUS: 'Статус не змінений',
    RUNNING: 'Сервер запущений',
    THIS_USER_ALREADY_EXISTS: 'Такий користувач вже існує',
    TRY_AGAIN_LATER: 'Будь ласка спробуйте пізніше',
};
